### PR TITLE
Poll hup

### PR DESCRIPTION
**Pull request by agordon**

### CODE REVIEW

**Comment by arachsys** [comment]
This repository has chosen to disable pull requests.

**Comment by arachsys** [comment]
A. Gordon <notifications@github.com> wrote:

> • contain: detect HUP and exit (don't fail)
> https://patch-diff.githubusercontent.com/raw/arachsys/containers/pull/3.patch

Interesting. I expected the read() to return zero in this case and  
everything to be terminated as normal, but I guess something different is  
happening for some reason.

We process the POLLHUP as well as the POLLIN because a different bug report  
described a busy-spinning console handler following the EOF:

   https://github.com/arachsys/containers/commit/44fa23235a5cf09bf5a59a0e0341dcf317210a2e

I think there are a few different cases here I should test fully and make  
sure we handle.

   - init process exits without closing stdout;
   - stdout closed by the init process but it carries on running;
   - stdout held open by the init process while /dev/console opened and closed in the container;
   - stdout closed by the init process then /dev/console opened and closed in the container.

I'll add that to my list to test out and check what happens in each case!

Best wishes,

Chris.

**Comment by arachsys** [comment]
Chris Webb <chris@arachsys.com> wrote:

> A. Gordon <notifications@github.com> wrote:
> 
>> • contain: detect HUP and exit (don't fail)
>> https://patch-diff.githubusercontent.com/raw/arachsys/containers/pull/3.patch
> 
> Interesting. I expected the read() to return zero in this case and
> everything to be terminated as normal, but I guess something different
> is happening for some reason.

I think the behaviour here is quite racy. If I run your test command I
see lots of this:

    $ contain / /bin/seq 1 && echo ok || echo fail
    ok
    $

and this

    $ ./contain / /bin/seq 1 && echo ok || echo fail
    1
    ok
    $

but not the

    $ contain DIR /bin/seq 1 && echo ok || echo fail
    1
    ./contain: read: Input/output error
    fail
    $

case you see with your container.

This inconsistency suggests some kind of race between the container init
process exiting and the console supervisor doing its thing to me?

Something like this is probably right to avoid the strange behaviour on
POLLHUP:

    diff --git a/console.c b/console.c
    index 79c552a..dd402e4 100644
    --- a/console.c
    +++ b/console.c
    @@ -111,7 +111,13 @@ int supervise(pid_t child, int console) {
             if (errno != EAGAIN && errno != EINTR)
               error(1, errno, "poll");
     
    -    if (fds[0].revents & (POLLIN | POLLHUP)) {
    +    if (fds[0].revents & POLLHUP)
    +      fds[0].events = 0;
    +
    +    if (fds[1].revents & POLLHUP)
    +      fds[1].events = 0;
    +
    +    if (fds[0].revents & POLLIN) {
            while ((length = read(console, buffer, sizeof(buffer))) < 0)
              if (errno != EAGAIN && errno != EINTR)
               error(1, errno, "read");
    @@ -125,7 +131,7 @@ int supervise(pid_t child, int console) {
           }
         }
     
    -    if (fds[1].revents & (POLLIN | POLLHUP)) {
    +    if (fds[1].revents & POLLIN) {
           while ((length = read(STDIN_FILENO, buffer, sizeof(buffer))) < 0)
             if (errno != EAGAIN && errno != EINTR)
               error(1, errno, "read");

but it doesn't fix the inconsistent behaviour:

    $ ./contain / /bin/seq 1 && echo ok || echo fail
    1
    ok
    $ ./contain / /bin/seq 1 && echo ok || echo fail
    ok
    $ ./contain / /bin/seq 1 && echo ok || echo fail
    1
    ok
    $ 

I'll have to dig into this a bit further.

Cheers,

Chris.

**Comment by arachsys** [comment]
Chris Webb <chris@arachsys.com> wrote:

> This inconsistency suggests some kind of race between the container init
> process exiting and the console supervisor doing its thing to me?
>
> Something like this [...] is probably right to avoid the strange  
> behaviour on
> POLLHUP, but it doesn't fix the inconsistent behaviour: [...].

Turns out that simple patches like the above aren't sufficient, e.g. for an  
example of a container which stress tests the console behaviour a bit more,  
use

     #!/bin/bash
     exec 0>&- 1>&- 2>&-
     sleep 1
     echo foo >/dev/console
     sleep 1
     exit

The console supervisor will see a POLLHUP when the init process closes the  
console, but it carries on running, and reopens it. If we stop monitoring  
the console on the first close, we'll never copy any more output.

There's also a nasty case where I'm only able to read the last data from  
the console *after* the contained process exits, so I probably need a last  
while() loop reading from the console and spitting out to stdout at the end  
of that console supervisor, or continue looping round with poll() until the  
console output is definitely exhausted.

Looks like you've found the tip of an iceberg. I need to investigate the  
detailed behaviour and rewrite to match it...

Cheers,

Chris.

**Comment by arachsys** [comment]
PS I see the Github web app is trying to post up this discussion, but  
mangling the quoted code and inline patches rather horribly. It would be  
infinitely preferable to send patches, etc. by email to chris@arachsys.com  
so they don't get molested by the web app.

I'll continue to respond to emails via Github in this thread, but I'm  
afraid I can't control the mess Github makes of the messages.

(If I could kill the web-based 'pull request' thing on the Github repos, I  
would. I tried using http://nopullrequests.com but it only does an  
auto-close and a message after the fact rather than removing the button. As  
it is, I'm considering ditching Github altogether to avoid people trying to  
use their horrible corruption of normal pull requests.)

Cheers,

Chris.

**Comment by arachsys** [comment]
The interaction between ptys and poll() is quite complicated, ambiguously
specified and it's hard to do a simple poll() loop that accounts correctly
for cases where the console is opened and closed multiple times inside the
container.

Fortunately, there's a good way to tame the behaviour. If we hold the
slave device open ourselves, we bypass almost all of the corner cases.

Could you try the patch below and see if it fixes the problems you saw?

diff --git a/console.c b/console.c
index 79c552a..36a76c8 100644
--- a/console.c
+++ b/console.c
@@ -74,7 +74,7 @@ void setconsole(char *name) {
 
 int supervise(pid_t child, int console) {
   char buffer[PIPE_BUF];
-  int signals, status;
+  int signals, slave, status;
   sigset_t mask;
   ssize_t count, length, offset;
   struct pollfd fds[3];
@@ -99,6 +99,8 @@ int supervise(pid_t child, int console) {
   atexit(restoremode);
   rawmode();
 
+  slave = open(ptsname(console), O_RDWR);
+
   fds[0].fd = console;
   fds[0].events = POLLIN;
   fds[1].fd = STDIN_FILENO;
@@ -111,36 +113,28 @@ int supervise(pid_t child, int console) {
         if (errno != EAGAIN && errno != EINTR)
           error(1, errno, "poll");
 
-    if (fds[0].revents & (POLLIN | POLLHUP)) {
-      while ((length = read(console, buffer, sizeof(buffer))) < 0)
+    if (fds[0].revents & POLLIN) {
+      if ((length = read(console, buffer, sizeof(buffer))) < 0)
         if (errno != EAGAIN && errno != EINTR)
           error(1, errno, "read");
-      if (length > 0) {
-        for (offset = 0; length > 0; offset += count, length -= count)
-          while ((count = write(STDOUT_FILENO, buffer + offset, length)) < 0)
-            if (errno != EAGAIN && errno != EINTR)
-              error(1, errno, "write");
-      } else {
-        fds[0].events = 0;
-      }
+      for (offset = 0; length > 0; offset += count, length -= count)
+        while ((count = write(STDOUT_FILENO, buffer + offset, length)) < 0)
+          if (errno != EAGAIN && errno != EINTR)
+            error(1, errno, "write");
     }
 
-    if (fds[1].revents & (POLLIN | POLLHUP)) {
-      while ((length = read(STDIN_FILENO, buffer, sizeof(buffer))) < 0)
+    if (fds[1].revents & POLLIN) {
+      if ((length = read(STDIN_FILENO, buffer, sizeof(buffer))) < 0)
         if (errno != EAGAIN && errno != EINTR)
           error(1, errno, "read");
-      if (length > 0) {
-        for (offset = 0; length > 0; offset += count, length -= count)
-          while ((count = write(console, buffer + offset, length)) < 0)
-            if (errno != EAGAIN && errno != EINTR)
-              error(1, errno, "write");
-      } else {
-        fds[1].events = 0;
-      }
+      for (offset = 0; length > 0; offset += count, length -= count)
+        while ((count = write(console, buffer + offset, length)) < 0)
+          if (errno != EAGAIN && errno != EINTR)
+            error(1, errno, "write");
     }
 
     if (fds[2].revents & POLLIN) {
-      while (read(signals, buffer, sizeof(buffer)) < 0)
+      if (read(signals, buffer, sizeof(buffer)) < 0)
         if (errno != EAGAIN && errno != EINTR)
           error(1, errno, "read");
       if (waitpid(child, &status, WNOHANG) > 0)
@@ -150,5 +144,6 @@ int supervise(pid_t child, int console) {
   }
 
   close(signals);
+  close(slave);
   return WIFEXITED(status) ? WEXITSTATUS(status) : EXIT_FAILURE;
 }

**Comment by agordon** [comment]
Hello @arachsys,

First, thanks for looking carefully into this.

second,
I should mention that for my original intent (of running a filter program with STDIN/STDOUT inside `contain`), using your `-c` option does the trick without any error:
```
$ seq 10 15 | contain -c ./foo /bin/wc -l
6
```
while there is some strange regarding connecting the STDIN file-descriptor to the container without `-c` - I'm not sure if that's intentional or not:

```
$ seq 10 | contain foo /bin/wc -l
1
2
3
4
5
6
7
8
9
10
[ hangs forever ]
```

**Comment by arachsys** [comment]
A. Gordon <notifications@github.com> wrote:

> while there is some strange regarding connecting the STDIN file-descriptor to the container without -c - I'm not sure if that's intentional or not:
> 
> $ seq 10 | contain foo /bin/wc -l
> 1
> 2
> 3
> 4
> 5
> 6
> 7
> 8
> 9
> 10
> [ hangs forever ]

Ah yes, that one probably is intentional: EOF on stdin doesn't show up as EOF on the console mainly so that you can do

  contain /mnt/image /bin/init </dev/null >/tmp/container.log

to run a full system without causing the getty listening on the console to crash. I added the -c option specifically to cover the case where you wanted to use a contain in a pipeline without all the overhead and special behaviour of a console terminal. Perhaps the console-less behaviour should have been the default and adding the console required an option, but it depends what people use it for the most really.

Cheers,

Chris.

**Comment by arachsys** [comment]
Hi. I've pushed a series of fixes to issues that this discussion has uncovered. Hopefully they cure the problems you saw?

In general, using the console tty won't work well in a pipeline, e.g. because it ignores EOF and (by default) echoes input like any other terminal. So:

    $ echo foo | contain / /bin/cat
    foo
    foo
    [hangs waiting for more input]
    ^C

whereas

    $ echo foo | contain -c / /bin/cat
    foo
    $

works as normal.

Best wishes,

Chris.

**Pull request closed without merging**
